import type { User, Project, Task, Comment } from './types';

export const users: User[] = [
  { id: 'u1', name: 'Sarah Chen', role: 'Product Manager' },
  { id: 'u2', name: 'Alex Rodriguez', role: 'Engineer' },
  { id: 'u3', name: 'Emma Wilson', role: 'Engineer' },
  { id: 'u4', name: 'James Kim', role: 'Engineer' },
  { id: 'u5', name: 'Maya Patel', role: 'Engineer' },
];

const comments: Comment[] = [
  {
    id: 'c1',
    content: 'This looks great! Let\'s prioritize this for the next sprint.',
    authorId: 'u1',
    taskId: 't1',
    createdAt: new Date('2025-09-20T10:00:00'),
    updatedAt: new Date('2025-09-20T10:00:00'),
  },
  {
    id: 'c2',
    content: 'I\'ll start working on the API endpoints.',
    authorId: 'u2',
    taskId: 't1',
    createdAt: new Date('2025-09-20T11:00:00'),
    updatedAt: new Date('2025-09-20T11:00:00'),
  },
  {
    id: 'c3',
    content: 'Database schema is ready for review.',
    authorId: 'u3',
    taskId: 't2',
    createdAt: new Date('2025-09-21T09:00:00'),
    updatedAt: new Date('2025-09-21T09:00:00'),
  },
];

const tasks: Task[] = [
  {
    id: 't1',
    title: 'Setup authentication system',
    description: 'Implement JWT-based authentication for the application',
    status: 'In Progress',
    assigneeId: 'u2',
    projectId: 'p1',
    comments: [comments[0], comments[1]],
    createdAt: new Date('2025-09-19T08:00:00'),
  },
  {
    id: 't2',
    title: 'Design database schema',
    description: 'Create the initial database schema for all entities',
    status: 'In Review',
    assigneeId: 'u3',
    projectId: 'p1',
    comments: [comments[2]],
    createdAt: new Date('2025-09-18T10:00:00'),
  },
  {
    id: 't3',
    title: 'Create landing page',
    description: 'Design and implement the marketing landing page',
    status: 'To Do',
    assigneeId: 'u4',
    projectId: 'p1',
    comments: [],
    createdAt: new Date('2025-09-20T14:00:00'),
  },
  {
    id: 't4',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    status: 'Done',
    assigneeId: 'u5',
    projectId: 'p1',
    comments: [],
    createdAt: new Date('2025-09-17T09:00:00'),
  },
  {
    id: 't5',
    title: 'Implement search functionality',
    description: 'Add search capabilities to the product catalog',
    status: 'In Progress',
    assigneeId: 'u2',
    projectId: 'p2',
    comments: [],
    createdAt: new Date('2025-09-21T10:00:00'),
  },
  {
    id: 't6',
    title: 'Shopping cart integration',
    description: 'Integrate shopping cart with payment gateway',
    status: 'To Do',
    assigneeId: 'u3',
    projectId: 'p2',
    comments: [],
    createdAt: new Date('2025-09-21T11:00:00'),
  },
  {
    id: 't7',
    title: 'Product reviews system',
    description: 'Allow customers to leave reviews and ratings',
    status: 'To Do',
    assigneeId: 'u4',
    projectId: 'p2',
    comments: [],
    createdAt: new Date('2025-09-21T12:00:00'),
  },
  {
    id: 't8',
    title: 'Mobile app wireframes',
    description: 'Create wireframes for the mobile application',
    status: 'In Review',
    assigneeId: 'u1',
    projectId: 'p3',
    comments: [],
    createdAt: new Date('2025-09-19T15:00:00'),
  },
  {
    id: 't9',
    title: 'Push notification service',
    description: 'Implement push notifications for iOS and Android',
    status: 'To Do',
    assigneeId: 'u5',
    projectId: 'p3',
    comments: [],
    createdAt: new Date('2025-09-20T16:00:00'),
  },
  {
    id: 't10',
    title: 'Offline mode support',
    description: 'Enable app functionality in offline mode',
    status: 'To Do',
    projectId: 'p3',
    comments: [],
    createdAt: new Date('2025-09-21T08:00:00'),
  },
];

export const projects: Project[] = [
  {
    id: 'p1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with modern design and improved UX',
    tasks: tasks.filter(t => t.projectId === 'p1'),
  },
  {
    id: 'p2',
    name: 'E-Commerce Platform',
    description: 'Build a scalable e-commerce platform with advanced features',
    tasks: tasks.filter(t => t.projectId === 'p2'),
  },
  {
    id: 'p3',
    name: 'Mobile App Development',
    description: 'Native mobile application for iOS and Android platforms',
    tasks: tasks.filter(t => t.projectId === 'p3'),
  },
];